name: Run Test
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18]
        mongodb-version: [4.4, 5.0, 6.0]
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Install Packages
        run: npm install

      - name: Run Lint
        run: npm run lint

      - name: Build
        run: npm run build
        env:
          CI: true

      - name: Test
        run: npm run test
        env:
          CI: true
          MONGO_URI: mongodb://127.0.0.1:27017/agenda-test
